[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
dcore = { workspace = true }
dioxus = { workspace = true }
lcore = { workspace = true }
manganis = { workspace = true }
validator = { version = "0.20", features = ["derive"] }
